///*
// * This file was generated by the Gradle "init" task.
// *
// * This is a general purpose Gradle build.
// * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
// */
//
////import com.jfrog.bintray.gradle.BintrayExtension
////import com.jfrog.bintray.gradle.tasks.BintrayUploadTask
//
plugins {
    base
//    id("kotlinx-serialization").version("1.3.41").apply(false)
//    idea
}
//
//subprojects {
//    val suparnaturalVersion = "1.0.3"
//
//    repositories {
//        google()
//        jcenter()
//    }
//
//    apply(plugin = "idea")
//
//    group = "com.suparnatural"
//    version = suparnaturalVersion
//
//    idea.module {
//        isDownloadJavadoc = true
//        isDownloadSources = true
//    }
//
//}