name: Master-Build

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - actions 


jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: brew install kotlin
    - name: Utilities
      uses: suparngp/android-emulator-runner@release/v3
      with:
        api-level: 28
        keep: true
